steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/blumen-vision-app', '.']

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/blumen-vision-app']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'blumen-vision-app'
      - '--image'
      - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/blumen-vision-app'
      - '--region'
      - 'southamerica-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'

images:
  - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/blumen-vision-app'

options:
  logging: CLOUD_LOGGING_ONLY
